version: '3.7'
services:
  psql:
    image: repository.dimas-maryanto.com:8086/postgres:12.3
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: bootcamp
      POSTGRES_DB: bootcamp
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - pg_network
volumes:
  pg_data:
networks:
  pg_network:
